name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
    - name: setup cmake
      run: sudo apt install cmake

    - name: build
      run: |
        cmake -S . -B build
        cmake --build build
      
    - name: run
      run: build/test-monitor

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: create coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: ./*.html
        retention-days: 7
